//! Sidecar annotation store with versioned envelope and migrate-or-quarantine.
//!
//! Architecture decisions implemented here:
//! - A3/C4: `schema_version: 1` in the sidecar envelope from v1.
//! - C5: Migration policy — known versions migrate-in-place; unknown/future
//!   versions are quarantined (renamed to `.bak`) and a non-destructive
//!   warning is returned.  Data is NEVER silently discarded.
//! - A12/C13: Sidecar path helpers delegate to `crate::paths::sidecar_path`.
//! - C8: `block_level` status variant for Mermaid/table/footnote anchors that
//!   cannot be mapped to source character offsets.
//!
//! # Sidecar schema (v1)
//! ```json
//! {
//!   "schema_version": 1,
//!   "doc_content_hash": "<sha256 hex>",
//!   "general_notes": "…",
//!   "annotations": [
//!     {
//!       "id": "uuid-style-string",
//!       "line_start": 5,
//!       "line_end": 7,
//!       "char_start": 0,
//!       "char_end": 42,
//!       "quoted_text": "the selected text",
//!       "context_before": "line before",
//!       "context_after": "line after",
//!       "body": "reviewer comment",
//!       "status": "anchored",
//!       "created_at": "2025-01-01T00:00:00Z",
//!       "updated_at": "2025-01-01T00:00:00Z"
//!     }
//!   ]
//! }
//! ```

use serde::{Deserialize, Serialize};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// Current schema version written by this code.
pub const CURRENT_SCHEMA_VERSION: u32 = 1;

/// Status of a single annotation anchor.
///
/// Matches the IPC contract string values: "anchored" | "detached" | "block_level".
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AnchorStatus {
    /// The anchor is still valid and has been (re)confirmed against the doc.
    Anchored,
    /// The anchor could not be re-matched after a document edit.  The
    /// annotation is preserved but shown with a "detached" badge in the UI.
    Detached,
    /// The anchor refers to a transformed block (Mermaid diagram, table,
    /// footnote) where source character offsets are unavailable.  The anchor
    /// is keyed to a block ID instead.  Per C8 ruling.
    BlockLevel,
}

impl Default for AnchorStatus {
    fn default() -> Self {
        AnchorStatus::Anchored
    }
}

/// A single annotation on a document.
///
/// This struct is the canonical on-disk representation and MUST remain in sync
/// with the IPC contract types in `ipc.rs` / `ipc.ts`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Annotation {
    /// Unique ID (UUID-style; generated by caller).
    pub id: String,

    /// Starting line (0-indexed, matching the IPC contract).
    pub line_start: u32,
    /// Ending line (0-indexed, inclusive, matching the IPC contract).
    pub line_end: u32,

    /// Starting character offset within `line_start`.
    #[serde(default)]
    pub char_start: u32,
    /// Ending character offset within `line_end`.
    #[serde(default)]
    pub char_end: u32,

    /// The exact text that was selected when the annotation was created.
    pub quoted_text: String,

    /// Up to 3 lines of context **before** the selection (used for re-anchoring).
    #[serde(default)]
    pub context_before: String,
    /// Up to 3 lines of context **after** the selection (used for re-anchoring).
    #[serde(default)]
    pub context_after: String,

    /// The reviewer's comment body.
    pub body: String,

    /// Whether the anchor is currently valid.
    #[serde(default)]
    pub status: AnchorStatus,

    /// ISO 8601 creation timestamp.
    pub created_at: String,
    /// ISO 8601 last-updated timestamp.
    pub updated_at: String,
}

/// The top-level sidecar envelope (v1).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sidecar {
    /// Schema version — always written as `1` by this code.
    /// T2.2/A3: defaults to `0` on deserialization so that valid JSON without
    /// this field is treated as a v0 sidecar and migrated in-place rather than
    /// quarantined (matches `settings.rs` `unwrap_or(0)` policy).
    #[serde(default)]
    pub schema_version: u32,

    /// sha256 hex digest of the document content at the time annotations were
    /// last saved.  Used as the content-hash short-circuit in re-anchoring.
    pub doc_content_hash: String,

    /// General (unanchored) notes about the document.
    #[serde(default)]
    pub general_notes: String,

    /// All annotations for this document.
    #[serde(default)]
    pub annotations: Vec<Annotation>,
}

impl Sidecar {
    /// Create a new empty sidecar for a document with the given content hash.
    pub fn new(doc_content_hash: impl Into<String>) -> Self {
        Sidecar {
            schema_version: CURRENT_SCHEMA_VERSION,
            doc_content_hash: doc_content_hash.into(),
            general_notes: String::new(),
            annotations: Vec::new(),
        }
    }
}

/// The outcome of loading a sidecar file.
#[derive(Debug)]
pub enum LoadResult {
    /// Successfully loaded (and possibly migrated in-place).
    Loaded(Sidecar),
    /// No sidecar file exists at `path` — return a fresh empty sidecar.
    NotFound(Sidecar),
    /// The sidecar had an unknown/future schema version.  The file has been
    /// renamed to `<path>.bak` and this variant carries a warning message.
    /// The caller should surface the warning and let the user decide how to
    /// proceed (e.g., reset to empty or manually inspect the `.bak`).
    Quarantined {
        bak_path: PathBuf,
        warning: String,
        fallback: Sidecar,
    },
}

/// Error type for annotation store operations.
#[derive(Debug, thiserror::Error)]
pub enum AnnotationError {
    #[error("I/O error: {0}")]
    Io(#[from] io::Error),

    #[error("JSON parse error in sidecar: {0}")]
    Json(#[from] serde_json::Error),
}

/// Load annotations for `doc_path`.
///
/// Derives the sidecar path via `crate::paths::sidecar_path`, then:
/// 1. If missing → `LoadResult::NotFound` with a fresh empty sidecar.
/// 2. If present with `schema_version == 1` → `LoadResult::Loaded`.
/// 3. If present with an unknown/future version → quarantine (rename to `.bak`)
///    and return `LoadResult::Quarantined` with a warning.  Never discards data.
///
/// `current_doc_hash` is the sha256 hash of the doc content the caller has
/// already read; used to populate the fallback sidecar on not-found.
pub fn load_annotations(
    doc_path: &Path,
    current_doc_hash: &str,
) -> Result<LoadResult, AnnotationError> {
    let sidecar_path = crate::paths::sidecar_path(doc_path);
    load_annotations_from_path(&sidecar_path, current_doc_hash)
}

/// Like `load_annotations` but accepts an explicit sidecar path.
/// Useful for testing without needing a real doc path.
pub fn load_annotations_from_path(
    sidecar_path: &Path,
    current_doc_hash: &str,
) -> Result<LoadResult, AnnotationError> {
    if !sidecar_path.exists() {
        return Ok(LoadResult::NotFound(Sidecar::new(current_doc_hash)));
    }

    let raw = fs::read_to_string(sidecar_path)?;

    // T2.2/A3 two-pass schema parse (mirrors settings.rs `unwrap_or(0)`):
    //
    // Pass 1: attempt a full Value parse to distinguish malformed JSON from
    // valid JSON that merely has a missing/null schema_version field.
    //
    //   • parse fails  → quarantine (malformed JSON, never migrate-on-corrupt)
    //   • parse succeeds → extract schema_version (missing or null → treat as 0,
    //                      migrate in-place just like settings.rs)
    //
    // This fixes the bug where peek_schema_version() returned None for BOTH
    // malformed JSON and valid JSON missing schema_version, causing valid
    // but version-less sidecars to be quarantined instead of migrated (C-PEEK-1).
    let value: serde_json::Value = match serde_json::from_str(&raw) {
        Ok(v) => v,
        Err(_) => {
            // Malformed JSON — quarantine immediately; do NOT attempt migration.
            return quarantine(sidecar_path, current_doc_hash, "sidecar JSON is malformed");
        }
    };

    // Extract schema_version from the parsed Value; absent/null → 0.
    let version: u32 = value
        .get("schema_version")
        .and_then(|v| v.as_u64())
        .map(|v| v as u32)
        .unwrap_or(0);

    match version {
        v if v == CURRENT_SCHEMA_VERSION => {
            // Known version — deserialize fully.
            let sidecar: Sidecar = serde_json::from_str(&raw)?;
            Ok(LoadResult::Loaded(sidecar))
        }
        v if v < CURRENT_SCHEMA_VERSION => {
            // Known *older* version (including 0 = missing field) — migrate
            // in-place (C5), mirroring the settings store's policy.  Missing
            // fields are filled by serde defaults; we bump the version and write
            // the upgrade back so the sidecar is self-healing.
            // If the payload cannot be deserialized even after we know it's
            // valid JSON, quarantine rather than discard (never lose data).
            match serde_json::from_str::<Sidecar>(&raw) {
                Ok(mut sidecar) => {
                    sidecar.schema_version = CURRENT_SCHEMA_VERSION;
                    save_annotations_to_path(sidecar_path, &sidecar)?;
                    Ok(LoadResult::Loaded(sidecar))
                }
                Err(_) => quarantine(
                    sidecar_path,
                    current_doc_hash,
                    &format!(
                        "sidecar with schema_version {} could not be migrated to {}",
                        v, CURRENT_SCHEMA_VERSION
                    ),
                ),
            }
        }
        v => {
            // Unknown/future version — quarantine.
            quarantine(
                sidecar_path,
                current_doc_hash,
                &format!(
                    "sidecar has schema_version {} which is not supported by this version of Revenant (max supported: {}). \
                     The file has been preserved as a backup.",
                    v, CURRENT_SCHEMA_VERSION
                ),
            )
        }
    }
}

/// Save annotations for `doc_path`.
///
/// Derives the sidecar path from `doc_path` and writes the sidecar as JSON.
pub fn save_annotations(doc_path: &Path, sidecar: &Sidecar) -> Result<(), AnnotationError> {
    let sidecar_path = crate::paths::sidecar_path(doc_path);
    save_annotations_to_path(&sidecar_path, sidecar)
}

/// Like `save_annotations` but accepts an explicit sidecar path.
pub fn save_annotations_to_path(
    sidecar_path: &Path,
    sidecar: &Sidecar,
) -> Result<(), AnnotationError> {
    let json = serde_json::to_string_pretty(sidecar)?;

    // Atomic write: serialize to a sibling temp file, then rename over the
    // target. A crash mid-write leaves the previous sidecar intact instead of a
    // half-written (corrupt) file — honoring the "never lose annotations"
    // guarantee even on power loss.
    let mut tmp = sidecar_path.as_os_str().to_owned();
    tmp.push(".tmp");
    let tmp_path = PathBuf::from(tmp);

    fs::write(&tmp_path, json)?;
    fs::rename(&tmp_path, sidecar_path)?;
    Ok(())
}

// ── Internal helpers ──────────────────────────────────────────────────────────

/// Pick a backup path that does not clobber an existing backup.
///
/// Returns `<path>.bak` if free; otherwise the first free `<path>.bak.1`,
/// `<path>.bak.2`, … so an earlier quarantine's backup is never overwritten.
fn next_available_backup_path(sidecar_path: &Path) -> PathBuf {
    let mut base = sidecar_path.as_os_str().to_owned();
    base.push(".bak");
    let base = PathBuf::from(base);

    if !base.exists() {
        return base;
    }

    for n in 1u32.. {
        let mut candidate = base.as_os_str().to_owned();
        candidate.push(format!(".{n}"));
        let candidate = PathBuf::from(candidate);
        if !candidate.exists() {
            return candidate;
        }
    }

    // Unreachable in practice (u32::MAX iterations), but keep the type total.
    base
}

/// Rename `sidecar_path` to a non-colliding `<path>.bak` (or `<path>.bak.N`)
/// and return a `Quarantined` result.
fn quarantine(
    sidecar_path: &Path,
    current_doc_hash: &str,
    reason: &str,
) -> Result<LoadResult, AnnotationError> {
    let bak_path = next_available_backup_path(sidecar_path);

    fs::rename(sidecar_path, &bak_path)?;

    Ok(LoadResult::Quarantined {
        bak_path,
        warning: format!(
            "Revenant could not load the annotations sidecar: {}. \
             The original file has been preserved at '{}'.",
            reason,
            sidecar_path.display()
        ),
        fallback: Sidecar::new(current_doc_hash),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn sample_sidecar(doc_hash: &str) -> Sidecar {
        Sidecar {
            schema_version: 1,
            doc_content_hash: doc_hash.to_string(),
            general_notes: "some notes".to_string(),
            annotations: vec![Annotation {
                id: "ann-1".to_string(),
                line_start: 5,
                line_end: 7,
                char_start: 0,
                char_end: 13,
                quoted_text: "selected text".to_string(),
                context_before: "line 4".to_string(),
                context_after: "line 8".to_string(),
                body: "This needs revision".to_string(),
                status: AnchorStatus::Anchored,
                created_at: "2025-01-01T00:00:00Z".to_string(),
                updated_at: "2025-01-01T00:00:00Z".to_string(),
            }],
        }
    }

    fn write_sidecar_json(dir: &TempDir, name: &str, json: &str) -> PathBuf {
        let path = dir.path().join(name);
        fs::write(&path, json).unwrap();
        path
    }

    // ── load / save round-trip ────────────────────────────────────────────────

    #[test]
    fn round_trip_v1_sidecar() {
        let dir = TempDir::new().unwrap();
        let sidecar_path = dir.path().join("doc.md.annotations.json");
        let original = sample_sidecar("deadbeef");

        save_annotations_to_path(&sidecar_path, &original).unwrap();
        let result = load_annotations_from_path(&sidecar_path, "deadbeef").unwrap();

        match result {
            LoadResult::Loaded(loaded) => {
                assert_eq!(loaded.schema_version, 1);
                assert_eq!(loaded.doc_content_hash, "deadbeef");
                assert_eq!(loaded.general_notes, "some notes");
                assert_eq!(loaded.annotations.len(), 1);
                assert_eq!(loaded.annotations[0].id, "ann-1");
            }
            other => panic!("expected Loaded, got {:?}", other),
        }
    }

    #[test]
    fn load_not_found_returns_empty_sidecar() {
        let dir = TempDir::new().unwrap();
        let sidecar_path = dir.path().join("nonexistent.md.annotations.json");
        let result = load_annotations_from_path(&sidecar_path, "myhash").unwrap();
        match result {
            LoadResult::NotFound(s) => {
                assert_eq!(s.doc_content_hash, "myhash");
                assert!(s.annotations.is_empty());
            }
            other => panic!("expected NotFound, got {:?}", other),
        }
    }

    // ── quarantine (C5) ───────────────────────────────────────────────────────

    #[test]
    fn future_schema_version_is_quarantined() {
        let dir = TempDir::new().unwrap();
        let future_json = r#"{
            "schema_version": 99,
            "doc_content_hash": "abc",
            "general_notes": "important",
            "annotations": []
        }"#;
        let sidecar_path =
            write_sidecar_json(&dir, "doc.md.annotations.json", future_json);

        let result = load_annotations_from_path(&sidecar_path, "current_hash").unwrap();

        match result {
            LoadResult::Quarantined { bak_path, warning, fallback } => {
                // .bak file must exist with the original data.
                assert!(bak_path.exists(), ".bak file should be created");
                let bak_contents = fs::read_to_string(&bak_path).unwrap();
                assert!(
                    bak_contents.contains("\"important\""),
                    "original data must be preserved in .bak"
                );
                // Original sidecar should be gone.
                assert!(!sidecar_path.exists(), "original sidecar should be renamed");
                // Warning must mention the issue.
                assert!(warning.contains("schema_version") || warning.contains("not supported"));
                // Fallback is a fresh empty sidecar.
                assert!(fallback.annotations.is_empty());
                assert_eq!(fallback.doc_content_hash, "current_hash");
            }
            other => panic!("expected Quarantined, got {:?}", other),
        }
    }

    #[test]
    fn older_schema_version_migrates_in_place() {
        // A v0 sidecar (predating some field additions) must migrate in-place
        // and be rewritten at the current version — NOT quarantined (C5 parity
        // with the settings store).
        let dir = TempDir::new().unwrap();
        let v0_json = r#"{
            "schema_version": 0,
            "doc_content_hash": "abc",
            "general_notes": "keep me",
            "annotations": []
        }"#;
        let sidecar_path = write_sidecar_json(&dir, "doc.md.annotations.json", v0_json);

        let result = load_annotations_from_path(&sidecar_path, "current_hash").unwrap();

        match result {
            LoadResult::Loaded(s) => {
                assert_eq!(s.schema_version, CURRENT_SCHEMA_VERSION);
                assert_eq!(s.general_notes, "keep me");
            }
            other => panic!("expected Loaded (migrated), got {:?}", other),
        }

        // The on-disk file must have been rewritten at the current version.
        let on_disk = fs::read_to_string(&sidecar_path).unwrap();
        assert!(on_disk.contains("\"schema_version\": 1"));
        // No .bak — migration, not quarantine.
        let bak = dir.path().join("doc.md.annotations.json.bak");
        assert!(!bak.exists(), "migration must not create a .bak");
    }

    #[test]
    fn malformed_json_is_quarantined() {
        let dir = TempDir::new().unwrap();
        let sidecar_path =
            write_sidecar_json(&dir, "bad.md.annotations.json", "not json at all");

        let result = load_annotations_from_path(&sidecar_path, "hash").unwrap();
        assert!(
            matches!(result, LoadResult::Quarantined { .. }),
            "malformed JSON should be quarantined"
        );
        // .bak should exist.
        let bak = dir.path().join("bad.md.annotations.json.bak");
        assert!(bak.exists());
    }

    // ── schema_version field ──────────────────────────────────────────────────

    #[test]
    fn new_sidecar_has_version_1() {
        let s = Sidecar::new("hash");
        assert_eq!(s.schema_version, CURRENT_SCHEMA_VERSION);
        assert_eq!(CURRENT_SCHEMA_VERSION, 1);
    }

    #[test]
    fn anchor_status_serializes_as_snake_case() {
        let json = serde_json::to_string(&AnchorStatus::Detached).unwrap();
        assert_eq!(json, "\"detached\"");
        let json = serde_json::to_string(&AnchorStatus::Anchored).unwrap();
        assert_eq!(json, "\"anchored\"");
        let json = serde_json::to_string(&AnchorStatus::BlockLevel).unwrap();
        assert_eq!(json, "\"block_level\"");
    }

    // ── T2.2: Two-pass schema parse (A3/C-PEEK-1) ────────────────────────────

    /// Valid JSON that is missing the `schema_version` field should migrate
    /// in-place (treated as version 0), NOT quarantine.  This was the bug
    /// fixed by T2.2: the old `peek_schema_version` returned `None` for both
    /// malformed JSON and valid-JSON-missing-field.
    #[test]
    fn valid_json_missing_schema_version_migrates_not_quarantines() {
        let dir = TempDir::new().unwrap();
        // Valid JSON but no schema_version field.
        let json_no_version = r#"{
            "doc_content_hash": "abc123",
            "general_notes": "must be preserved",
            "annotations": []
        }"#;
        let sidecar_path = write_sidecar_json(&dir, "noversion.md.annotations.json", json_no_version);

        let result = load_annotations_from_path(&sidecar_path, "abc123").unwrap();

        // Must be Loaded (migrated), NOT Quarantined.
        match result {
            LoadResult::Loaded(s) => {
                assert_eq!(s.schema_version, CURRENT_SCHEMA_VERSION,
                    "migrated sidecar must have current schema_version");
                assert_eq!(s.general_notes, "must be preserved",
                    "general_notes must survive migration");
            }
            LoadResult::Quarantined { .. } => {
                panic!("valid JSON missing schema_version must migrate, not quarantine");
            }
            LoadResult::NotFound(_) => {
                panic!("unexpected NotFound");
            }
        }

        // The on-disk file must have been rewritten at the current version.
        let on_disk = fs::read_to_string(&sidecar_path).unwrap();
        assert!(on_disk.contains("\"schema_version\": 1"),
            "migrated sidecar must have schema_version: 1 on disk");

        // No .bak must exist.
        let bak = dir.path().join("noversion.md.annotations.json.bak");
        assert!(!bak.exists(), "migration must not create a .bak file");
    }

    /// Malformed JSON (not valid JSON at all) must still be quarantined.
    /// This is the other half of T2.2 — the two passes keep both behaviors.
    #[test]
    fn malformed_json_still_quarantines_after_two_pass_fix() {
        let dir = TempDir::new().unwrap();
        let sidecar_path =
            write_sidecar_json(&dir, "malformed.md.annotations.json", "{ not : valid json !!!");

        let result = load_annotations_from_path(&sidecar_path, "hash").unwrap();

        match result {
            LoadResult::Quarantined { bak_path, .. } => {
                assert!(bak_path.exists(), ".bak must be created for malformed JSON");
            }
            other => {
                panic!("malformed JSON must quarantine, got {:?}", other);
            }
        }
    }
}
